### ISSUE TITLE
Investigate using setgroups()

### ISSUE THREAD

**Issue by sionescu** [sionescu/libfixposix#10]
A lint check in OBS gives this message:

W: missing-call-to-setgroups-before-setuid /usr/lib64/libfixposix.so.3.0.0
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.

**Comment by decathorpe** [comment]
I'm working on packaging your project for fedora, and came across this issue, as well. It also looks like it has been promoted from an rpmlint warning to an error:

`E: missing-call-to-setgroups-before-setuid /usr/lib64/libfixposix.so.3.2.0`

**Comment by sionescu** [comment]
Thank you, I will look into it.

**Comment by sionescu** [comment]
cc0a1709ff9a removes the SETUID/SETGID options so this bug is no longer valid.
