### ISSUE TITLE
bitset.h is missing from the release (v0.4.0) tarball

### ISSUE THREAD

**Issue by ilovezfs** [sionescu/libfixposix#12]
Not sure if you're aware, but the release tarball is missing bitset.h, which causes build failure:
```
  CC       src/lib/resource.lo
  CC       src/lib/sendfile.lo
  CC       src/lib/syslog.lo
src/lib/bitset.c:29:10: fatal error: 'bitset.h' file not found
#include "bitset.h"
         ^
1 error generated.
make[1]: *** [src/lib/bitset.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
src/lib/spawn_file_actions.c:35:10: fatal error: 'bitset.h' file not found
#include "bitset.h"
         ^
1 error generated.
make[1]: *** [src/lib/spawn_file_actions.lo] Error 1
make: *** [all] Error 2
```

**Comment by sionescu** [comment]
Thank you. I created a new release. If you are using any of the Linux distributions listed at https://build.opensuse.org/project/show/home:sionescu then you can already use prebuilt packages.

**Comment by ilovezfs** [comment]
@sionescu Thanks! I'm actually one of the Homebrew maintainers, and was working on transitioning the formula to use the release tarball instead of the source archive tarball when I noticed this.

**Comment by ilovezfs** [comment]
:green_apple: https://github.com/Homebrew/homebrew-core/pull/2319

Thanks!
