### ISSUE TITLE
lfp3 debian 8 package broken?

### ISSUE THREAD

**Issue by attila-lendvai** [sionescu/libfixposix#14]
i just installed lfp from

```
deb http://download.opensuse.org/repositories/home:/sionescu/Debian_8/ ./
```

and this is the file list in the libfixposix3 package:

```
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libfixposix3
/usr/share/doc/libfixposix3/README.md
/usr/share/doc/libfixposix3/changelog.gz
/usr/share/doc/libfixposix3/copyright
```

i.e. the .so is not included? (the error that made me to look was that
the .so was not found by SBCL)

is it something i do, or the package is indeed broken?

**Comment by sionescu** [comment]
The package is indeed broken. I'll try to fix it as soon as possible.

**Comment by attila-lendvai** [comment]
@sionescu any chance for fixing this? the packages are still broken, looks like Debian9 also.

**Comment by sionescu** [comment]
This was fixed a while ago.
