### ISSUE TITLE
Debian package "libfixposix0" does not work with iolib

### ISSUE THREAD

**Issue by dcespin** [sionescu/libfixposix#16]
I used "apt-get install libfixposix-dev" on debian 8 to install libfixposix, and then I used quicklisp to install CLWS (websockets library) which depends on iolib. However, trying to run a websockets server crashed somewhere in iolib with an "unhandled memory fault". 

Cloning the git repo for libfixposix and installing it manually fixed the problem. This is pretty easy to do, so perhaps you could put a note in the README for iolib that if problems arise with the debian package, building and installing it manually may help.

**Comment by sionescu** [comment]
Done. Thanks for the suggestion.
