### ISSUE TITLE
API/ABI changes review for libfixposix

### ISSUE THREAD

**Issue by lvc** [sionescu/libfixposix#17]
The review of API/ABI changes for libfixposix since 0.2.1 version: https://abi-laboratory.pro/tracker/timeline/libfixposix/

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker. Hope it will be helpful for users and maintainers of the library.

![libfixposix-1](https://cloud.githubusercontent.com/assets/1517837/25384971/64eec70e-29d3-11e7-884b-834409d19144.png)
![libfixposix-2](https://cloud.githubusercontent.com/assets/1517837/25384977/6a660602-29d3-11e7-8933-4bae2ba6669c.png)

## Environment
* Linux x86_64
* GCC 4.9
* libfixposix 0.2.1 and higher

**Comment by sionescu** [comment]
Thank you.
