### ISSUE TITLE
syntax error near unexpected token `CHECK,'

### ISSUE THREAD

**Issue by nalzok** [sionescu/libfixposix#20]
I got the following error trying to configure this port:

```
$ cd /opt/local/var/macports/build/_private_var_local_ports_devel_libfixposix/libfixposix/work/libfixposix-0.4.3

$  sudo ./configure
Password:
configure: srcdir:   .
configure: builddir:
configure: CPPFLAGS:
configure: CFLAGS:
configure: LDFLAGS:
configure: WARNING: you should configure in a separate build directory
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes

 === IRRELEVANT OUTPUT OMITTED ===

checking for getpeereid... yes
./configure: line 13721: syntax error near unexpected token `CHECK,'
./configure: line 13721: `    PKG_CHECK_MODULES(CHECK, check >= 0.9.4)'
```

For more details, please see https://trac.macports.org/ticket/59125

**Comment by sionescu** [comment]
Is this still an issue ? If yes, try re-generating ./configure like this: autoreconf -f -i . The bundled configure script was generated on Linux, so it could be that the generated syntax doesn't work with whatever shell OSX deploys as /bin/sh.

**Comment by nalzok** [comment]
Thanks for the reply! This error seems to be fixed in the portfile now. Closing...

**Comment by byteit101** [comment]
Because I just ran into this, this is caused by not having pkgconfig installed. Installing pkgconfig solved the issue

**Comment by sionescu** [comment]
@byteit101 Thanks for the hint, I added a check for pkg-config.
