### ISSUE TITLE
Add rlimit lfp_spawn attribute

### ISSUE THREAD

**Issue by sionescu** [sionescu/libfixposix#27]
See https://github.com/jruby/jruby/issues/6552.

**Comment by headius** [comment]
Hey there! I wanted to check in and see what the chances are to get this and other recent additions into a release of libfixposix we can use in JRuby. We are pushing toward a big release at the end of the month and would love to show off how LFP has made JRuby's process-spawning more compatible with the standard CRuby (which uses fork/exec).

I have been working with @byteit101 to get his LFP-related Ruby code packaged up, and the main question we have right now is the release plan: do we wait for an official release from you or ship a soft fork with the changes we need right now?

Please let us know if we can help move this forward in any way!

**Comment by sionescu** [comment]
@headius I'll add this and make a release by the end of the week.
