### ISSUE TITLE
packaging clarification

### ISSUE THREAD

**Issue by attila-lendvai** [sionescu/libfixposix#7]
Stelian,

could you please add either an INSTALL file or extend the README with some words on how to install the packaged version and what is its status in the main distributions?

as far as i understand lfp reached the repos of the main distros, but there's only and old (2011) version in those repos. your repo (http://download.opensuse.org/repositories/home:/sionescu/Ubuntu_Trusty/) seems to have 0.3.0 which seems to be newer. BTW, this repo is also not mentioned in the README.

if you can squeeze in the time needed then a short update of the README could greatly simplify the users' lives.

thanks for your work!

**Comment by sionescu** [comment]
I added a short paragraph to README.md. See if you like it.

**Comment by attila-lendvai** [comment]
that helps, thanks!

and the signing key?

`
W: GPG error: http://download.opensuse.org ./ Release: The following signatures were invalid: KEYEXPIRED 1382659836
`

**Comment by sionescu** [comment]
Try re-importing the key, and change the repository URL, since now they all use numeric IDs: http://download.opensuse.org/repositories/home:/sionescu/

**Comment by sionescu** [comment]
Fetch keys 88A9D6FD and 8858438C from e.g. pgp.mit.edu. You should be able to verify the trust chain. Then gpg --export --armored 8858438C | sudo apt-key add -

**Comment by attila-lendvai** [comment]
thanks, this worked:
`
gpg --recv-keys 8858438C
`
`
gpg --export --armor 8858438C | sudo apt-key add -
`

(and the same for the other key)
