### ISSUE TITLE
configure error on CentOS 5.8 Final 64bit

### ISSUE THREAD

**Issue by muyinliu** [sionescu/libfixposix#9]
```
cd libfixposix-master
./configure --prefix=/usr/local
```
Error message here:
```=>
checking for getpeerucred... no
checking whether SO_PEERCRED is declared... yes
./configure: line 12195: syntax error near unexpected token `CHECK,'
./configure: line 12195: `    PKG_CHECK_MODULES(CHECK, check >= 0.9.4)'
```

Note: I compiled and installed `check` v0.10.0(because CentOS 5 is too old that yum only installed `check-devel-0.9.3-5.fc6`):
```
cd check-0.10.0
./configure --prefix=/usr/local
make && sudo make install
```
without any Error.

Note2: `autoreconf -i -f` without any Error.

**Comment by sionescu** [comment]
Thank you for the report. I'll try to bundle check, since it's just a few files and used only for testing.

**Comment by muyinliu** [comment]
Thanks.
I commented line 12195 in file `configure` and pass the `./configure`, finally `make` success.
